### ISSUE TITLE
Usable with Python 3.6?

### ISSUE THREAD

**Issue by jmclemo6** [cdorsey/canvas-uploader#1]
Currently using Python 3.6.2 and am getting a ``KeyError`` on line 24 of ``UserInterface.py``:
```
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    class_id = UserInterface.get_course()
  File "C:\Users\jmcle\cs302Labs\Labs\canvas\UserInterface.py", line 24, in get_course
    print("[{0}] {1}".format(i + 1, response.json()[i]['name']))
KeyError: 'name'
```
Is this due to the Python version or was there a change in the Canvas API in the last year or so?

**Comment by jmclemo6** [comment]
Ah, apparently I have a course without a name in my courses, so I just had to check to make sure the name existed.
